HRM/Models/Entity/Users/User.cs
using System.ComponentModel.DataAnnotations;

namespace HRM.Models.Entity
{
    public class User
    {
        public int Id { get; set; }

        public string FullName { get; set; }

        [Required] public string UserName { get; set; }

        [Required] [EmailAddress] public string Email { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Password must be least 6 character long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }

        public bool IsActive { get; set; }
    }
}

HRM/Models/ErrorViewModel.cs
using System;

namespace HRM.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HRM/Models/HRMDbContext.cs
using HRM.Models.Entity;
using Microsoft.EntityFrameworkCore;

namespace HRM.Models
{
    public class HRMDbContext : DbContext
    {
        public HRMDbContext(DbContextOptions<HRMDbContext> options) : base(options)
        {
        }

        public DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).HasColumnName("Id");
                entity.Property(e => e.UserName).HasColumnName("UserName");
                entity.Property(e => e.FullName).HasColumnName("FullName");
                entity.Property(e => e.PassWord).HasColumnName("PassWord");
                entity.Property(e => e.IsActive).HasColumnName("IsActive");
                entity.Property(e => e.Email).HasColumnName("Email");
            });
        }
    }
}

HRM/Models/MapProfile.cs
using AutoMapper;
using HRM.Models.Entity;
using HRM.Models.ViewModel;

namespace HRM.Models
{
    public class MapProfile : Profile
    {
        public MapProfile()
        {
            CreateMap<User, UserViewModel>()
                .ForMember(d => d.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(d => d.FullName, opt => opt.MapFrom(src => src.FullName))
                .ForMember(d => d.UserName, opt => opt.MapFrom(src => src.UserName))
                .ForMember(d => d.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(d => d.PassWord, opt => opt.MapFrom(src => src.PassWord))
                .ForMember(d => d.IsActive, opt => opt.MapFrom(src => src.IsActive));
            CreateMap<UserViewModel, User>()
                .ForMember(d => d.Id, opt => opt.MapFrom(src => src.Id))
                .ForMember(d => d.FullName, opt => opt.MapFrom(src => src.FullName))
                .ForMember(d => d.UserName, opt => opt.MapFrom(src => src.UserName))
                .ForMember(d => d.Email, opt => opt.MapFrom(src => src.Email))
                .ForMember(d => d.PassWord, opt => opt.MapFrom(src => src.PassWord))
                .ForMember(d => d.IsActive, opt => opt.MapFrom(src => src.IsActive));
        }
    }
}

HRM/Models/ViewModel/User/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace HRM.Models.ViewModel
{
    public class UserViewModel
    {
        public int Id { get; set; }

        public string FullName { get; set; }

        [Required] public string UserName { get; set; }

        [Required] [EmailAddress] public string Email { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = "Password must be least 6 character long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string PassWord { get; set; }

        public bool IsActive { get; set; }
    }
}

HRM/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HRM.Models;

namespace HRM.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

HRM/Controllers/UserController.cs
using System.Collections.Generic;
using HRM.Models.Entity;
using HRM.Service.UserService;
using Microsoft.AspNetCore.Mvc;

namespace HRM.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public ViewResult Index()
        {
            return
                View(_userService.GetAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(User user)
        {
            _userService.Add(user);
            _userService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var getId = _userService.GetById(id);
            return View(getId);
        }

        [HttpPost]
        public IActionResult Edit(User user)
        {
            _userService.Update(user);
            _userService.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _userService.Delete(id);
            _userService.Save();
            return RedirectToAction("Index");
        }
    }
}

HRM/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HRM</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HRM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - HRM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

HRM/Views/User/Create.cshtml
@model HRM.Models.Entity.User
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PassWord" class="control-label"></label>
                    <input asp-for="PassWord" class="form-control" />
                    <span asp-validation-for="PassWord" class="text-danger"></span>
                </div>             
                <div class="form-group">
                    <label asp-for="IsActive" class="control-label"></label>
                    <input asp-for="IsActive" class="form-control" />
                    <span asp-validation-for="IsActive" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="text-dark btn btn-primary" asp-area="" asp-controller="User" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

HRM/Views/User/Edit.cshtml
@model HRM.Models.Entity.User

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="User" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="Id">
                <div class="form-group">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="UserName" class="control-label"></label>
                    <input asp-for="UserName" class="form-control" />
                    <span asp-validation-for="UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PassWord" class="control-label"></label>
                    <input asp-for="PassWord" class="form-control" />
                    <span asp-validation-for="PassWord" class="text-danger"></span>
                </div>             
                <div class="form-group col-xs-12">
                    <label asp-for="IsActive" class="control-label"></label>
                    <input asp-for="IsActive" class="form-control" />
                    <span asp-validation-for="IsActive" class="text-danger"></span>
                </div>
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class=" text-dark btn btn-primary" asp-area="" asp-controller="User" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
    
</div>

HRM/Views/User/Index.cshtml
@using HRM.Models.Entity
@model IEnumerable<HRM.Models.Entity.User>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>User List</h2>
                        <a asp-action="Create" class="btn btn-primary">Create New User</a>

                    </div>
                    <div class="x_content">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>First Name</th>
                                <th>Last Name</th>
                                <th>Email </th>
                                <th>Password </th>
                                <th>Role </th>
                                <th>Active </th>
                                <th>Note </th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                             
                                <tr class="text-left">
                                    @* <td> @Html.DisplayFor(modelItem => item.StudentId)</td> *@
                                    <td> @Html.DisplayFor(modelItem => item.FullName)</td>
                                    <td> @Html.DisplayFor(modelItem => item.UserName)</td>
                                    <td> @Html.DisplayFor(modelItem => item.Email)</td>
                                    <td> @Html.DisplayFor(modelItem => item.PassWord)</td>
                                    <td> @Html.DisplayFor(modelItem => item.IsActive)</td>
                                    <td>
                                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                        <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.Id">Delete</a>  
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>